#include "lcd.h"
#include "icu.h"
#include "Ultrasonic.h"
#include <avr/io.h> /* To use the SREG register */
#include "gpio.h"
#include "std_types.h"
#include <util/delay.h>

uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;
uint16 distance;
/*
 * Description:This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void)//call back function
{
	g_edgeCount++;
	if (g_edgeCount == 1) {
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if (g_edgeCount == 2) {
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
	}
	else if(g_edgeCount == 4)
	    {
		LCD_sendCommand(LCD_SET_CURSOR_LOCATION);
		//Icu_DeInit(); /* Disable ICU Driver */
		g_edgeCount = 0;
		LCD_displayString("Distance = ");
		/* calculate the period */
		distance = Ultrasonic_readDistance();
		/* display the period on LCD screen */
		LCD_intgerToString(distance);
		LCD_displayString(" cm");
	}
}


int main(void)
{
	LCD_init();
	/* Enable Global Interrupt I-Bit */
	SREG |= (1<<7);

	Ultrasonic_init();
    while(1)
    {
    	Ultrasonic_readDistance();
    }
}
